Convert unsupported characters
codeforamerica/form-flow pull request #455
Opened 2023-11-27 17:01 UTC by enyia21

2023-11-27 22:32 UTC, coltborg commented on src/main/java/formflow/library/pdf/PDFBoxFieldFiller.java
> +        System.out.println("test");
Do you still need to print out `test`?
```suggestion
```

2023-11-27 22:42 UTC, coltborg requested changes
Tested and thing work as I expected. Left a comment to remove a `println`.

![2023-11-27 at 16 40 13@2x](https://github.com/codeforamerica/form-flow/assets/9101728/fab4f7d1-3d45-4620-b906-4f1e28f08126)

2023-11-28 16:45 UTC, coltborg approved these changes

2023-11-28 17:16 UTC, bseeger commented
Is this one superseded by the one about OpenPDF?

2023-12-05 21:29 UTC, coltborg commented
@enyia21 I think we can close this PR now?

2023-12-05 21:52 UTC, spokenbird commented
Closing as we won't be usign this approach.

2023-12-05 21:52 UTC, closed without merging